### ISSUE TITLE
Merge duplicate imports

### ISSUE THREAD

**Issue by pmeier** [facebookexperimental/usort#107]
`usort` accepts the snippet below as sorted.

```python
from foo import bar
from foo import baz
from foo import baz, bar
```

while it can be shrank to

```python
from foo import baz, bar
```

Would it be possible to perform this automatically, so I don't have to pay attention to the imports if new ones are added?

**Comment by jreese** [comment]
This is already landed in main, for the upcoming [1.0](https://github.com/facebookexperimental/usort/milestone/2) release. There is a prerelease version v1.0.0b1 available that has this functionality if you would like to test and provide feedback. We are hoping to get the final 1.0 release ready by EOW or next.

**Comment by pmeier** [comment]
@jreese Merging works like a charm. Thanks a lot!

While trying this, I noted that `usort` now wraps lines. Running `usort format` with the latest beta release on

```python
from torch.utils.data.datapipes.iter import FileLister, FileLoader, Mapper, Shuffler, Filter
```

gives

```python
from torch.utils.data.datapipes.iter import (
    FileLister,
    FileLoader,
    Filter,
    Mapper,
    Shuffler,
)
```

This is problematic, because due to the last comma, `black` (used through `ufmt`) will no longer put these back on one line although our configured line length allows it. If I manually remove the comma again and run `black -l 120` on it, it gets reformatted to

```python
from torch.utils.data.datapipes.iter import FileLister, FileLoader, Filter, Mapper, Shuffler
```

which is what I expected from running `ufmt` in the first place.

**Comment by jreese** [comment]
If you have your black line-length configured in pyproject.toml, µsort should use that when deciding whether to expand (or collapse) multiline imports.

**Comment by pmeier** [comment]
It seems it doesn't. This is our [pyproject.toml](https://github.com/pytorch/vision/blob/main/pyproject.toml). Could you try to reproduce the behavior above?

**Comment by jreese** [comment]
#110 should fix this for you.
