### ISSUE TITLE
What is the difference between isort and this repo

### ISSUE THREAD

**Issue by csukuangfj** [facebookexperimental/usort#116]
Are there any advantages to use this repo over [isort](https://github.com/PyCQA/isort)?

**Comment by thatch** [comment]
isort and usort perform the same basic function, but usort's main goal is to Do The Right Thing (or close to it) without additional directives.  There are some examples in the first couple paragraphs of https://github.com/facebookexperimental/usort#readme
 that demonstrate how it avoids some classes of behavior changes that tools like isort can cause.

If there are specific questions that are not addressed in the readme, I'm happy to take a look.

**Comment by jreese** [comment]
A more explicit comparison is now available as part of the "Why µsort?" page: https://usort.readthedocs.io/en/latest/why.html
