### ISSUE TITLE
Usort from STDIN

### ISSUE THREAD

**Issue by croqaz** [facebookexperimental/usort#155]
Hi! Thanks for making this tool!
I think it would be useful to allow formatting of imports from a stream coming from another app, eg: I want to integrate this in Emacs and I would have to select some text and pass it to usort.
I suppose there are other ways that this can be useful.
Is it planned sometime?
Thank you!

**Comment by jreese** [comment]
It's not well documented, but running `usort format -` will format from stdin.

**Comment by croqaz** [comment]
I can confirm that it works! Thanks!
