### ISSUE TITLE
Respect names case when sorting (CONSTANT, Class, function/variable_name)

### ISSUE THREAD

**Issue by Bobronium** [facebookexperimental/usort#158]
## Problem

`usort diff` (no config) produces this diff:
```py
-from .names import ABBR_TO_FULL_NAME, FULL_NAME_TO_ABBR, Path, deminify, minify
+from .names import ABBR_TO_FULL_NAME, deminify, FULL_NAME_TO_ABBR, minify, Path
```
However, I find the way it was ordered already is more consistent and "right". 
`isort` respects that order and doesn't change it by default.

## Proposal
Add option to preserve `CONSTANT`, `Class`, `function`/`variable_name` order when sorting.

**Comment by jreese** [comment]
µsort is intentionally using case-insensitive (specifically casefolded) sorting for both module names and imported names. We believe that is a usability benefit, as it means "frog", "Frog", and "FROG" will all sort next to each other, without a user needing to think about which implicit "section" of an import statement they will find an element in. We also do not intend to offer options to change this behavior, as that complicates the implementation and makes it harder to test and reason about safety of the resulting changes.

See the "comparison to isort" and "non-goals" sections of the user guide for further explanation: https://usort.readthedocs.io/en/stable/why.html

**Comment by thatch** [comment]
Some additional context on how we got to this state:

1. We want "import a" and "import B" to sort naturally.  There are some real-world examples like "Queue" from py2, case-insensitive filesystems, and another one that we've seen internally that benefit from this.
2. We want "from x import a" and "from x import B" to sort naturally.  We can't tell easily whether "a" and "B" are modules or names within a module without introspecting the source.  We don't want to require the source to be available, thus this needs to be chosen based only on the strings "a" and "B" (actually "x.a" and "x.B").
3. We want to use the same rule for non-from imports.

The only choice that's straightforward to document and doesn't require the source is "all names are sorted case-insensitively."  I wasn't a fan at first, but John convinced me this was much simpler to explain than something special-casey like "from imports are case-sensitive but everything else isn't."
