### ISSUE TITLE
Support for Python 3.10's match operator

### ISSUE THREAD

**Issue by IvanovCosmin** [facebookexperimental/usort#185]
Currently the match operator is not supported because of the version of libcst that is in use. https://github.com/facebookexperimental/usort/pull/180 
0.4.1 only has support for Python up to 3.8, while 0.4.2 (and up) has support for every other Python version.
Is it likely to be fixed in the near future?

**Comment by thatch** [comment]
usort only specifies a min version that is the lowest that passes our tests; you're free to upgrade.  Similar to how ufmt advises pinning black and usort, you can also do so for libcst: https://ufmt.omnilib.dev/en/stable/#install

Let me know if I misunderstand the problem -- an example repo would be helpful.

**Comment by IvanovCosmin** [comment]
Totally got it! Thanks!
