### ISSUE TITLE
General directive customization

### ISSUE THREAD

**Issue by thatch** [facebookexperimental/usort#33]
Some directives are standalone, e.g.

```
# type STANDALONE
# fmt: off
```

Others come before the line (or statement) they affect

```
# type LEADING
# pyre-ignore: ...
import x
```

While others must happen at end of line

```
# type TRAILING_FIRST_LINE
from x import (  # isort:skip
  y,
  # type TRAILING
  z,  # noqa: F123
)  # hypothetical TRAILING_LAST_LINE
```

These basic types can be detected by prefix match and handled when ordering.  Right now leading comments (in a block) are special-cased in [`partition_leading_lines`](https://github.com/facebookexperimental/usort/blob/main/usort/sorting.py#L293) but ones that are of the LEADING type need to be excepted from that and kept with the statement.

These should be configurable, but with defaults for common tools.

**Comment by jreese** [comment]
Going to close this, as we just universally move comments preceding imports now. I think that's easier to explain than trying to magically decide what should or shouldn't move with the import. Reopen if you disagree?
