### ISSUE TITLE
Improve error messages for parsing/syntax errors

### ISSUE THREAD

**Issue by jreese** [facebookexperimental/usort#44]
LibCST gives more information about these errors than we send to the user: https://libcst.readthedocs.io/en/latest/parser.html#syntax-errors

**Comment by thatch** [comment]
This was a conscious choice. The syntax error might be different depending on the version of the grammar we attempted with. Which do you pick to show it there's both a print statement and a walrus?

See docstring https://github.com/facebookexperimental/usort/blob/main/usort/util.py#L51

And where this confused me in black, https://github.com/psf/black/issues/1158

**Comment by jreese** [comment]
I think that if parsing fails on all compatible versions, then showing the error from the latest version of the grammar is a reasonable compromise, and giving *anything* is going to be more useful than choosing to show nothing in fear of picking the wrong thing. Andres also pointed out that the error message as-is can be quite confusing to users who aren't aware of how usort is trying to parse with all supported LibCST grammars:

> What I mean is that `No version could parse <data>` is going to confuse users

My suggestion is to replace this with something like `Error parsing <path>:<line> - <message>`, and maybe we can bikeshed more from there.
