### ISSUE TITLE
Support excluding files from a configuration file

### ISSUE THREAD

**Issue by pmeier** [facebookexperimental/usort#62]
As of now `usort` does not provide an option to exclude certain files from a configuration file. There is the `# usort:skip` (or `# isort:skip`) directive, but this gets tedious fast if one wants to skip a complete directory or files based on a pattern.

There are several options from other formatters / linters how to achieve this. Since `usort` should be used with a code formatter and `black` is an obvious choice, IMO it would be a good idea to adhere to their `--exclude` behavior, i.e. regular expression matching.

**Comment by jreese** [comment]
I'm curious: what's the use case for skipping entire files or directories? Part of the reason for µsort is being safe enough that it can sort everything by default. Are these files generated, and are they still being formatted by black? Beyond that, how are you expecting this to behave, especially when using the µsort API, like with µfmt? Does it need a matching config entry in `pyproject.toml`?

µfmt (along a couple other tools in the omnilib family) uses another library I wrote, [trailrunner](https://trailrunner.omnilib.dev/en/stable/), to walk the project tree, find relevant source files, and execute the appropriate logic in parallel using child processes. We had planned to switch µsort to trailrunner as well, and made some progress in PR #61.

Currently, trailrunner just looks for a `.gitignore` file to decide which files to skip, but it could be useful to add an explicit list of patterns (or a PathSpec object), to supplement the existing behavior. Perhaps even a helper function to automatically pull that out of a pyproject.toml when given a section/key name? This could then be used for both µsort and µfmt.

**Comment by pmeier** [comment]
> Beyond that, how are you expecting this to behave, especially when using the µsort API, like with µfmt? Does it need a matching config entry in `pyproject.toml`?

Yes. Going by the `black` format, that would look something like

```toml
[tool.usort]

exclude = '''
/(
    my_package/foo
  | __init__.py
)/
'''
```

> I'm curious: what's the use case for skipping entire files or directories?

We are planning to use `ufmt` for a library and there are parts that should not be touched by any formatter. In our use case it would probably fine to let `usort` do its thing and only prevent `black` from running. Currently `ufmt` does not support skipping files. If it did, IMO it would better to be able to support it for both tools not just `black`. Hence this issue.

**Comment by NicolasHug** [comment]
> We are planning to use ufmt for a library and there are parts that should not be touched by any formatter

To expand on that: we have a gallery of tutorials/examples in torchvision (e.g. [this one](https://pytorch.org/vision/stable/auto_examples/plot_visualization_utils.html#sphx-glr-auto-examples-plot-visualization-utils-py)) where style consistency isn't really necessary and even sometimes unwanted. Often for these notebook-style examples we want to have self-contained cells where each cell has its own imports when we introduce new tools. In some rare cases we may even want each cell to be cell-contained and fully copy-pastable, with possibly duplicated imports etc.

**Comment by pmeier** [comment]
I've opened omnilib/ufmt#12 to discuss only disabling `black` formatting, since this is the use case we are targeting right now. I still feel like this could be a good addition to `usort`. @jreese I'll leave up to you to close this or leave it opened.

**Comment by zsol** [comment]
One use case for excluding certain files: test fixtures. For LibCST I don't really want any formatting to be done on files that are just input to various tests.

**Comment by jreese** [comment]
Now that µsort is also using trailrunner, this is simple enough to include in 1.0.

**Comment by jreese** [comment]
@zsol I would still recommend setting up and using [µfmt](https://ufmt.omnilib.dev) instead of running black and µsort separately. Happy to send a PR to LibCST to make that happen.

**Comment by zsol** [comment]
Yep, we're using µfmt for LibCST and that's how I ultimately excluded these fixtures from all formatting (not just µsort). Thanks!
